name: Sync Fork and Update main

# This runs every 1st of the month at 04:01 UTC
on:
  schedule:
    - cron: '1 4 1 * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  update_fork:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: https://github.com/nothings/stb.git
          upstream_branch: master
          downstream_branch: stb
          token: ${{ secrets.WORKFLOW_TOKEN }}
          spawn_logs: false
  copy-to-branches:
    needs: update_fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.2
        env:
          branches: main
          key: stb
          files: stb_image.h
