name: Sync Fork and Update main

# This runs every 1st of the month at 04:01 UTC
on:
  schedule:
    - cron: '1 4 1 * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: https://github.com/nothings/stb.git
          upstream_branch: master
          downstream_branch: stb
          token: ${{ secrets.GITHUB_TOKEN }}
          spawn_logs: false
  copy-to-main:
    needs: update-fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Copy Updated stb Files
        env:
          COMMIT_MESSAGE: Copy updated files [Automated Action]
          COMMIT_AUTHOR: Github Action
          FILES: stb_image.h
        run: |
          mkdir -p include
          git config --global user.name "${{ env.COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git archive --format=tar stb | tar -x -C include
          cd include
          git add $FILES
          git commit -m "${{ env.COMMIT_MESSAGE }}"
          git push origin main
